# Run linters on code in repo to avoid common issues:
# * YAPF for Python scripts
name: Lint checks
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cclauss/Find-Python-syntax-errors-action@master
